name: gitlab-cloner-ci

on:
  push:
    branches:
      - main
      - develop
      - feat/**
      - chore/**
      - fix/**
  pull_request:
    branches:
      - main
      - develop
      - feat/**
      - chore/**
      - fix/**

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
    - uses: actions/checkout@v4

    - name: install git
      run: |
        apt-get update && apt-get install -y git
    
    - name: install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: run linting
      run: |
        echo "Running flake8..."
        flake8 gitlab-cloner.py
        echo "Running pylint..."
        pylint gitlab-cloner.py

    - name: run type checking
      run: |
        echo "Running mypy type checking..."
        python3 -m mypy gitlab-cloner.py

    - name: run basic tests
      run: |
        echo "Testing script execution..."
        python3 gitlab-cloner.py --help > /dev/null && echo "Script executes successfully"

    - name: run unit tests
      run: |
        echo "Running unit tests..."
        python3 -m pytest tests/ -v && echo "All unit tests passed!"

    - name: validate script
      run: python3 gitlab-cloner.py --help

